# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

warnings_are_errors: false
language: r
r:
  - oldrel
cache: packages
r_binary_packages:
  - devtools
  - roxygen2
  - testthat
